### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by Inesgor** [8go/pass-grave#2]
What a brilliant thing have you made my man. And the document is perfect for a noob like me. Kudos to you.

**Comment by Inesgor** [comment]
Two more points. First that you can make a "Makefile" to make it easier. I'd send a PR if i knew the syntax of Makefiles. 
Also, there is a typo when we open a grave. It says "You can now oerate..." instead of "You can now operate".

**Comment by 8go** [comment]
I am glad you like it. 

Thank you very much @Inesgor for contributing!  :heart: 

Applause and cheers also to @celenium !  :clap:

I merged PR #3 today. Sorry for the delay.

**Comment by 8go** [comment]
I gave some :clap: to you @Inesgor and @celenium   in the README.md. I hope you don't mind.
